### ISSUE TITLE
[BUG] CutomUserDetails에서 user_id가 null로 나오는 문제

### ISSUE THREAD

**Issue by jhYun505** [CampingOn/CampingOn-BE#146]
### 📝 버그 요약

로그인 후 캠핑장 인기 목록 조회 api 요청 시 user의 id가 Null이 나옴

### 🔄 재현 방법

1. Postman에서 회원가입
2. Postman으로 로그인
3. 캠핑장 인기 목록 조회 api 호출

### ✔️ 예상 동작

캠핑장 인기 목록이 조회된다

### ❌ 실제 동작

500 에러 발생. `CustomUserDetails.getId()`

### 🐾 관련 로그

```
java.lang.NullPointerException: Cannot invoke "site.campingon.campingon.common.jwt.CustomUserDetails.getId()" because "userDetails" is null
	at site.campingon.campingon.camp.controller.CampController.getPopularCamps(CampController.java:53)
	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
	at java.base/java.lang.reflect.Method.invoke(Method.java:580)
	at org.springframework.aop.support.AopUtils.invokeJoinpointUsingReflection(AopUtils.java:355)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.invokeJoinpoint(ReflectiveMethodInvocation.java:196)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:163)
	at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.proceed(CglibAopProxy.java:768)
	at org.springframework.aop.aspectj.AspectJAfterThrowingAdvice.invoke(AspectJAfterThrowingAdvice.java:64)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:184)
	at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.proceed(CglibAopProxy.java:768)
	at org.springframework.aop.framework.adapter.AfterReturningAdviceInterceptor.invoke(AfterReturningAdviceInterceptor.java:57)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:184)
	at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.proceed(CglibAopProxy.java:768)
	at org.springframework.aop.framework.adapter.MethodBeforeAdviceInterceptor.invoke(MethodBeforeAdviceInterceptor.java:58)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:184)
	at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.proceed(CglibAopProxy.java:768)
	at org.springframework.aop.interceptor.ExposeInvocationInterceptor.invoke(ExposeInvocationInterceptor.java:97)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:184)
	at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.proceed(CglibAopProxy.java:768)
	at org.springframework.aop.framework.CglibAopProxy$DynamicAdvisedInterceptor.intercept(CglibAopProxy.java:720)
	at site.campingon.campingon.camp.controller.CampController$$SpringCGLIB$$0.getPopularCamps(<generated>)
	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
	at java.base/java.lang.reflect.Method.invoke(Method.java:580)
	at org.springframework.web.method.support.InvocableHandlerMethod.doInvoke(InvocableHandlerMethod.java:255)
	at org.springframework.web.method.support.InvocableHandlerMethod.invokeForRequest(InvocableHandlerMethod.java:188)
	at org.springframework.web.servlet.mvc.method.annotation.ServletInvocableHandlerMethod.invokeAndHandle(ServletInvocableHandlerMethod.java:118)
	at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.invokeHandlerMethod(RequestMappingHandlerAdapter.java:926)
	at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.handleInternal(RequestMappingHandlerAdapter.java:831)
	at org.springframework.web.servlet.mvc.method.AbstractHandlerMethodAdapter.handle(AbstractHandlerMethodAdapter.java:87)
	at org.springframework.web.servlet.DispatcherServlet.doDispatch(DispatcherServlet.java:1089)
	at org.springframework.web.servlet.DispatcherServlet.doService(DispatcherServlet.java:979)
	at org.springframework.web.servlet.FrameworkServlet.processRequest(FrameworkServlet.java:1014)
	at org.springframework.web.servlet.FrameworkServlet.doGet(FrameworkServlet.java:903)
```

**Comment by jhYun505** [comment]
```java
  // 캠핑장 인기 목록 조회 (페이지네이션)
  @GetMapping("/popular")
  public ResponseEntity<Page<CampListResponseDto>> getPopularCamps(
      @RequestParam(defaultValue = "0") int page,
      @AuthenticationPrincipal CustomUserDetails userDetails
  ) {
    boolean hasKeywords = userKeywordRepository.existsByUserId(userDetails.getId());
    int pageSize = hasKeywords ? KEYWORD_MATCHED_PAGE_SIZE : DEFAULT_PAGE_SIZE;

    return ResponseEntity.ok(
        campService.getPopularCamps(userDetails.getId(), PageRequest.of(page, pageSize))
    );
  }
  ```
  
  - 원인: 캠핑장 인기 목록 조회 시에도 유저 정보를 받아오고 있어서 오류가 생기고 있습니다.
  - 로그인이 필요없는(`hasRole('USER')`가 아닌) api의 경우는 
  `@AuthenticationPrincipal CustomUserDetails userDetails`를 넣으시면 안됩니다!
  - 예시로 캠핑장 상세 조회 api에서는 userDetails를 받아오지 않는데,
  ```java
    // 캠핑장 상세 조회  -  찜 버튼 활성화 시 유저 확인 추가
  @GetMapping("/{campId}")
  public ResponseEntity<CampDetailResponseDto> getCampDetail(
      @PathVariable("campId") Long campId
  ) {
    return ResponseEntity.ok(campService.getCampDetail(campId));
  }
```
![스크린샷 2024-12-02 오후 3 51 17](https://github.com/user-attachments/assets/576f7426-d7c8-4fc2-bc49-61bb567e8db0)
- 정상 동작 하는 것을 확인 할 수 있습니다!


- Postman 사용 시 로그인이 필요한 경우에는 반드시  Auth 탭에서 Auth Type을 Bearer Token으로 설정해주셔야 자동으로 로그인시 발급받은 accessToken의 값이 들어오게 됩니다.
![스크린샷 2024-12-02 오후 3 55 03](https://github.com/user-attachments/assets/75db5aab-de6c-4396-a095-bb7858eed0be)

**Comment by chanjin23** [comment]
@jhYun505 감사합니다!
유저정보가 필요한 api를 사용하게 될경우 @AuthenticationPrincipal 을 사용하면 자동으로 인증이 된다는거죠?
만약 해당 api가 유저정보를 필요로 하게되는 api면 customUserDetails.getId 처럼 가지고와서 사용하면 되는건가요?

**Comment by jhYun505** [comment]
@chanjin23 사용하실 때는 CustomUserDetails 내부에 있는 값들을 가져와서 사용하시면 됩니다!
```java
    public CustomUserDetails(Long id, String email, String nickname, Role role, String password) {
        this.id = id;
        this.email = email;
        this.nickname = nickname;
        this.role = role;
        this.password = password;
    }
```
